version: "3.9"

services:
  auth-api:
    build: ./auth-api
    container_name: auth-api
    environment:
      - AUTH_API_PORT=8000
      - USERS_API_ADDRESS=http://users-api:8083
      - JWT_SECRET=PRFT
    ports:
      - "8000:8000"
    networks:
      - micro-net

  todos-api:
    build: ./todos-api
    container_name: todos-api
    environment:
      - TODO_API_PORT=8082
      - JWT_SECRET=PRFT
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    ports:
      - "8082:8082"
    depends_on:
      - redis
    networks:
      - micro-net

  log-message-processor:
    build: ./log-message-processor
    container_name: log-message-processor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis
    networks:
      - micro-net

  users-api:
    build: ./users-api
    container_name: users-api
    environment:
      - JWT_SECRET=PRFT
      - SERVER_PORT=8083
    ports:
      - "8083:8083"
    networks:
      - micro-net

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - PORT=8080
      - AUTH_API_ADDRESS=http://auth-api:8000
      - TODOS_API_ADDRESS=http://todos-api:8082
    ports:
      - "8080:8080"
    depends_on:
      - auth-api
      - todos-api
      - users-api
    networks:
      - micro-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge