name: Development Build (Local Simulation)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-only:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Detect changed microservice
        id: detect
        run: |
          echo "Detecting changed folder..."
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '/' | cut -d'/' -f1 | uniq | head -1)
          echo "Changed service: $CHANGED"
          echo "service=$CHANGED" >> $GITHUB_OUTPUT

      - name: Build Docker image (simulation)
        if: steps.detect.outputs.service != ''
        run: |
          SERVICE=${{ steps.detect.outputs.service }}
          IMAGE_NAME="${SERVICE}:latest"
          echo "Building Docker image for $SERVICE..."
          docker build -t $IMAGE_NAME ./$SERVICE
          echo "Build completed successfully for $SERVICE"

      - name: Install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-cli

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Restart ACI container group
        run: |
          echo "Restarting the entire ACI group..."
          az container restart \
            --resource-group microservicesRgJenniferCastro \
            --name microservices-group
